/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:32a85e8d-e6ca-484e-b99a-28733308aede",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_4y9c7i7SE",
    "aws_user_pools_web_client_id": "6vigpca22njs53f7la2mv2ng3h",
    "oauth": {}
};


export default awsmobile;
